version: '3.7'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erpnext
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnext
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

  frappe:
    build: .
    environment:
      SITE_NAME: site1.local
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      INSTALL_APPS: hrms
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis-cache
    volumes:
      - frappe-sites-vol:/home/frappe/frappe-bench/sites
      - frappe-assets-vol:/home/frappe/frappe-bench/sites/assets

volumes:
  mariadb-data:
  frappe-sites-vol:
  frappe-assets-vol:
