apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrms
  template:
    metadata:
      labels:
        app: hrms
    spec:
      containers:
      - name: hrms
        image: your-dockerhub-username/hrms:1.0.0
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
